# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'singleImgClassificationWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(941, 894)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 851, 651))
        self.groupBox.setObjectName("groupBox")
        self.Imglabel = QtWidgets.QLabel(self.groupBox)
        self.Imglabel.setGeometry(QtCore.QRect(30, 50, 781, 571))
        self.Imglabel.setText("")
        self.Imglabel.setObjectName("Imglabel")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(620, 690, 271, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Infolabel = QtWidgets.QLabel(self.groupBox_2)
        self.Infolabel.setGeometry(QtCore.QRect(20, 40, 461, 61))
        self.Infolabel.setText("")
        self.Infolabel.setObjectName("Infolabel")
        self.fileBtn = QtWidgets.QPushButton(Dialog)
        self.fileBtn.setGeometry(QtCore.QRect(60, 690, 271, 151))
        self.fileBtn.setObjectName("fileBtn")
        self.fileBtn2 = QtWidgets.QPushButton(Dialog)
        self.fileBtn2.setGeometry(QtCore.QRect(360, 690, 231, 151))
        self.fileBtn2.setObjectName("fileBtn2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Display Window"))
        self.groupBox_2.setTitle(_translate("Dialog", "Result"))
        self.fileBtn.setText(_translate("Dialog", "Select File"))
        self.fileBtn2.setText(_translate("Dialog", "Detailed Forecast Results"))
